### ISSUE TITLE
这是用过的最好的视号工具

### ISSUE THREAD

**Issue by asd6fds** [592767809/video_server#1]
漁滒你太有才了。昨天晚上用的时候，显示推送后台下载，但其实没有下载。没想到你那么快就更新了，现在正常使用。

**Comment by golegola** [comment]
66的渔哥，请问证书和代理都正常  唯独【key被重置经常失效 不弹出字样】  导致视频号无法下载。能否加个补丁进行修复  或者手动实现KEY被重置这一关键步骤呢？

**Comment by golegola** [comment]
由于key被重置经常失效 不弹出字样   于是各种折腾 ，重复安装证书 ，卸载微信重装 ，覆盖安装[video_server]，清理垃圾注册表后再次重新安装，依然不能解决问题。Cache_Data在微信登录前也清空了，对微信的版本有特殊要求吗？

**Comment by microka** [comment]
同上，证书和代理正常，但没见有弹出【微信视频号：key已被重置】这些字样，捕获不了微信客户端里面视频号的视频，微信版本3.9.5.89，能捕获谷歌浏览器浏览腾讯视频（虽然下载失败）。

**Comment by microka** [comment]
操作多几次，现在有提示【微信视频号：key已被重置】，但依然未能捕获视频号视频地址。

**Comment by golegola** [comment]
一番折腾后  把微信切换各种版本  （key重置已经解决）  但是浏览器捕获链接显示出来后，但推送失败。视频号推送链接不显无法下载

**Comment by 592767809** [comment]
> 由于key被重置经常失效 不弹出字样 于是各种折腾 ，重复安装证书 ，卸载微信重装 ，覆盖安装[video_server]，清理垃圾注册表后再次重新安装，依然不能解决问题。Cache_Data在微信登录前也清空了，对微信的版本有特殊要求吗？

用最新版就可以，【key被重置】没有显示只需要清空Cache_Data缓存目录就可以解决

**Comment by 592767809** [comment]
> 一番折腾后 把微信切换各种版本 （key重置已经解决） 但是浏览器捕获链接显示出来后，但推送失败。视频号推送链接不显无法下载

微信js代码更新导致原逻辑失效，待修复

**Comment by golegola** [comment]
经过渔哥的修复升级 1.0.1版本确实可以下载了，修复后上传超级快，太给力了！可是退出微信和video_server后 再次打开 又失效了 ！缓存数据包括目录先删了，打开server后，登录微信，key重置也没有弹出来。微信版本3.9.5.81

**Comment by golegola** [comment]
经过渔哥的修复升级 1.0.1版本确实可以下载了，修复后上传超级快，太给力了！可是退出微信和video_server后 再次打开 又失效了 ！缓存数据/包括目录Cache_Data先删了，打开server后，登录微信，key重置也没有弹出来。微信版本3.9.5.81

**Comment by golegola** [comment]
或许是我为了来这里回复内容，用第三方软件开VPN破坏了代理数值导致。不开我打不开此网页。于是我就卸载微信重装 把证书文件夹全部删除了，重新打开新的server 并安装证书由原来的（本地计算机）切换到当前用户后，恢复正常使用了！

**Comment by golegola** [comment]
渔哥你好！关于微信视频号下载，【当退出微信第二次登陆，KEY重置就失效无法弹出显示了】，但是我每次都是通过卸载微信后，重新安装就能恢复正常，这导致每次使用都得先卸载再安装。代理正常，C:\Users\用户命\AppData\Roaming\Tencent\WeChat\radium\web\profiles\multitab\Cache\每次都正常删除了仍然无效！
