### ISSUE TITLE
开启服务8777？无法重置视频号key

### ISSUE THREAD

**Issue by joker1396** [592767809/video_server#10]
![image](https://github.com/592767809/video_server/assets/127610637/671a63aa-2d3e-4af0-8b29-2108d2b8c302)
![image](https://github.com/592767809/video_server/assets/127610637/58ae6bb4-fdb3-4176-8fe7-a44d6a5fadb1)
之前使用是正常的，后来一段时间没用，再去使用的时候，会出现开启服务8777（这之前没有），同时按步骤清理Cache_Data,打开server,再打开微信，不会出现微信视频号：key被重置的消息
@渔哥，看到帮忙指点一下

**Comment by 592767809** [comment]
部分高版本的微信可能路径不一样，例如3.9.7.29，路径如下
C:\Users\【用户名】\AppData\Roaming\Tencent\WeChat\radium\web\profiles\multitab_【32位英文数字】\Cache\Cache_Data

**Comment by joker1396** [comment]
> 部分高版本的微信可能路径不一样，例如3.9.7.29，路径如下 C：\Users\【用户名】\AppData\Roaming\Tencent\WeChat\radium\web\profiles\multitab_【32位英文数字】\Cache\Cache_Data

就在这个路径下清空的，而且服务8777,之前没遇到过，是哪里出问题了吗

**Comment by 592767809** [comment]
> > 部分高版本的微信可能路径不一样，例如3.9.7.29，路径如下 C：\Users\【用户名】\AppData\Roaming\Tencent\WeChat\radium\web\profiles\multitab_【32位英文数字】\Cache\Cache_Data
> 
> 就在这个路径下清空的，而且服务8777,之前没遇到过，是哪里出问题了吗

你使用的微信客户端是什么版本，3.9.7.29测试正常。需要进入视频号或者点击视频详情才会出现

**Comment by joker1396** [comment]
> > > 部分高版本的微信可能路径不一样，例如3.9.7.29，路径如下 C：\Users\【用户名】\AppData\Roaming\Tencent\WeChat\radium\web\profiles\multitab_【32位英文数字】\Cache\Cache_Data
> > 
> > 
> > 就在这个路径下清空的，而且服务8777,之前没遇到过，是哪里出问题了吗
> 
> 你使用的微信客户端是什么版本，3.9.7.29测试正常。需要进入视频号或者点击视频详情才会出现

你好，我用截图复现了我的步骤
首先清空了cache_data的文件
![image](https://github.com/592767809/video_server/assets/127610637/76d61288-9133-4fb0-8ee3-a69a635046ac)
其次打开了video server 和m3u8 
检查了版本为3.9.7.29
![image](https://github.com/592767809/video_server/assets/127610637/e892d213-86ff-4c7b-a356-a58b31b7508f)
![image](https://github.com/592767809/video_server/assets/127610637/c22a775c-d44b-43aa-9fa3-49a946c68a33)
打开视频号的视频的时候，视频一直卡住不动，而且没有出现key重置
![image](https://github.com/592767809/video_server/assets/127610637/f3e6a936-5301-4336-a55d-2d011f1835df)

**Comment by 592767809** [comment]
> > > > 部分高版本的微信可能路径不一样，例如3.9.7.29，路径如下 C：\Users\【用户名】\AppData\Roaming\Tencent\WeChat\radium\web\profiles\multitab_【32位英文数字】\Cache\Cache_Data
> > > 
> > > 
> > > 就在这个路径下清空的，而且服务8777,之前没遇到过，是哪里出问题了吗
> > 
> > 
> > 你使用的微信客户端是什么版本，3.9.7.29测试正常。需要进入视频号或者点击视频详情才会出现
> 
> 你好，我用截图复现了我的步骤 首先清空了cache_data的文件 ![image](https://user-images.githubusercontent.com/127610637/279287725-76d61288-9133-4fb0-8ee3-a69a635046ac.png) 其次打开了video server 和m3u8 检查了版本为3.9.7.29 ![image](https://user-images.githubusercontent.com/127610637/279288106-e892d213-86ff-4c7b-a356-a58b31b7508f.png) ![image](https://user-images.githubusercontent.com/127610637/279288212-c22a775c-d44b-43aa-9fa3-49a946c68a33.png) 打开视频号的视频的时候，视频一直卡住不动，而且没有出现key重置 ![image](https://user-images.githubusercontent.com/127610637/279288371-f3e6a936-5301-4336-a55d-2d011f1835df.png)

尝试两个缓存文件都删除，或者在用户目录删除生成的证书缓存文件，然后重新安装证书

**Comment by firedfox** [comment]
也可能并没有问题，我也是同样的微信版本，在按步骤打开微信视频号之后，server界面上也没有任何反应，但在server.exe同级的video目录下，会正常保存全部的视频mp4文件
