### ISSUE TITLE
请问这个工具能下载直播回放么？

### ISSUE THREAD

**Issue by Cyiming** [592767809/video_server#16]
我自己抓包找不到m3u8地址了

**Comment by 592767809** [comment]
> 我自己抓包找不到m3u8地址了

暂不支持

**Comment by 592767809** [comment]
> 我自己抓包找不到m3u8地址了

测试直播回放也是mp4直连，并且没有加密。没有太大添加的必要

**Comment by Cyiming** [comment]
> > 我自己抓包找不到m3u8地址了
> 
> 测试直播回放也是mp4直连，并且没有加密。没有太大添加的必要

应该是加密的吧，我用小白点测试了下，只复制小白点解析的地址放在idm中，没有下载进度，得一直开软件才能下载。

**Comment by 592767809** [comment]
> > > 我自己抓包找不到m3u8地址了
> > 
> > 
> > 测试直播回放也是mp4直连，并且没有加密。没有太大添加的必要
> 
> 应该是加密的吧，我用小白点测试了下，只复制小白点解析的地址放在idm中，没有下载进度，得一直开软件才能下载。

没有加密，没有进度大概率是代理问题，可以尝试关闭软件、关闭代理，然后再下载
