### ISSUE TITLE
有的视频不能捕获，最新版本

### ISSUE THREAD

**Issue by asd6fds** [592767809/video_server#18]
今天更新了v1.0.5。开启服务 8777微信：HOOK功能已开启。
有的视频不能捕获。没有任何文字提示。
有的是能正常捕获的。

**Comment by 592767809** [comment]
必须进入到视频详情，或者刷新重试

**Comment by asd6fds** [comment]
谢谢你那么快回复。
我遇到不能捕获的都是视频号里面的。视频号的视频已经打开播放了，工具里没有捕获到。
当然不是所有都不能，视频号很多视频是可以捕获下载的。

















在 2024-01-11 14:10:58，"漁滒" ***@***.***> 写道：

必须进入到视频详情，或者刷新重试

**Comment by 592767809** [comment]
复现一下不能下载的视频时你的操作，提供一下不能下载的视频的标题，最好加个截图

**Comment by asd6fds** [comment]
一个小时砍完60只鸡鸭，她是怎么做到的？










都是常规操作，就是有一些不能捕获，有些可以





在 2024-01-11 16:08:14，"漁滒" ***@***.***> 写道：

复现一下不能下载的视频时你的操作，提供一下不能下载的视频的标题，最好加个截图

**Comment by 592767809** [comment]
确实有问题，下个版本更新

**Comment by asd6fds** [comment]
谢谢了



在 2024-01-11 16:44:56，"漁滒" ***@***.***> 写道：

确实有问题，下个版本更新

**Comment by chenqinzhao** [comment]
你好，能提供下1.0.4的版本链接吗。最先版下载不了。也是提示hook那个信息。

**Comment by 592767809** [comment]
尝试使用最新版下载

**Comment by asd6fds** [comment]
可以捕获下载了，试过多个视频号视频都可以了。
太感谢了

















在 2024-01-13 10:32:31，"漁滒" ***@***.***> 写道：

尝试使用最新版下载
