### ISSUE TITLE
无法下载微信视频号

### ISSUE THREAD

**Issue by netsonicyxf** [592767809/video_server#2]
最新版server显示
微信直播：开启直播弹幕测试功能
微信视频号：key已被重置

微信视频号在播放，但server窗口没有显示捕获连接。

**Comment by 592767809** [comment]
> 最新版server显示 微信直播：开启直播弹幕测试功能 微信视频号：key已被重置
> 
> 微信视频号在播放，但server窗口没有显示捕获连接。

必须点击进入到播放详情页才能捕获

**Comment by whj13142020** [comment]
老大，V1.0.1好像没有什么效果，没有检测到，视频下载不了，ps：我下载了最新的1.0.1版本，也建立了HOST文件
MyEmail: 3730862@qq.com

**Comment by asd6fds** [comment]
> 老大，V1.0.1好像没有什么效果，没有检测到，视频下载不了，ps：我下载了最新的1.0.1版本，也建立了HOST文件 MyEmail: [3730862@qq.com](mailto:3730862@qq.com) 我的电子邮件： 3730862@qq.com

视频号-推荐，下面的视频，直接点击是不能捕捉下载的。点其他地方的视频，或者分享后再点击就能下载

**Comment by asd6fds** [comment]
> 老大，V1.0.1好像没有什么效果，没有检测到，视频下载不了，ps：我下载了最新的1.0.1版本，也建立了HOST文件 MyEmail: [3730862@qq.com](mailto:3730862@qq.com) 我的电子邮件： 3730862@qq.com

视频号-推荐，下面的视频，直接点击是不能捕捉下载的。点其他地方的视频，或者分享后再点击就能下载

**Comment by whj13142020** [comment]
> > 老大，V1.0.1好像没有什么效果，没有检测到，视频下载不了，ps：我下载了最新的1.0.1版本，也建立了HOST文件 MyEmail: [3730862@qq.com](mailto:3730862@qq.com) 我的电子邮件： [3730862@qq.com](mailto:3730862@qq.com)
> 
> 视频号-推荐，下面的视频，直接点击是不能捕捉下载的。点其他地方的视频，或者分享后再点击就能下载

具体怎么操作？ 进入视频号后 ，点击搜索，然后点击搜索后的视频可以吗

**Comment by 592767809** [comment]
> > > 老大，V1.0.1好像没有什么效果，没有检测到，视频下载不了，ps：我下载了最新的1.0.1版本，也建立了HOST文件 MyEmail: [3730862@qq.com](mailto:3730862@qq.com) 我的电子邮件： [3730862@qq.com](mailto:3730862@qq.com)
> > 
> > 
> > 视频号-推荐，下面的视频，直接点击是不能捕捉下载的。点其他地方的视频，或者分享后再点击就能下载
> 
> 具体怎么操作？ 进入视频号后 ，点击搜索，然后点击搜索后的视频可以吗

在测试时只做了两种，第一种是点开【微信视频号】-【首页】然后进入到视频详情，第二种就是打开别人分享的视频号进入到视频详情

**Comment by whj13142020** [comment]
发现一个问题，“微信视频号：key已被重置”  这句话没有出现，是什么原因，有提示代理开启成功

**Comment by whj13142020** [comment]
漁滒，没有出现 “微信视频号：key已被重置” 是上面原因

从 Windows 版邮件发送

发件人: 漁滒
发送时间: 2023年7月9日 12:37
收件人: 592767809/video_server
抄送: whj13142020; Comment
主题: Re: [592767809/video_server] 无法下载微信视频号 (Issue #2)

老大，V1.0.1好像没有什么效果，没有检测到，视频下载不了，ps：我下载了最新的1.0.1版本，也建立了HOST文件 MyEmail: ***@***.*** 我的电子邮件： ***@***.***
视频号-推荐，下面的视频，直接点击是不能捕捉下载的。点其他地方的视频，或者分享后再点击就能下载
具体怎么操作？ 进入视频号后 ，点击搜索，然后点击搜索后的视频可以吗
在测试时只做了两种，第一种是点开【微信视频号】-【首页】然后进入到视频详情，第二种就是打开别人分享的视频号进入到视频详情

**Comment by 592767809** [comment]
> 发现一个问题，“微信视频号：key已被重置” 这句话没有出现，是什么原因，有提示代理开启成功

代理没有开启成功，或者是缓存没有被清理

**Comment by netsonicyxf** [comment]
> > 最新版server显示 微信直播：开启直播弹幕测试功能 微信视频号：key已被重置
> > 微信视频号在播放，但server窗口没有显示捕获连接。
> 
> 必须点击进入到播放详情页才能捕获

成功，感谢大神。

**Comment by whj13142020** [comment]
感谢漁滒，成功下载，这是我用过的最好的视频号下载软件，给你点赞！！！

从 Windows 版邮件发送

发件人: 漁滒
发送时间: 2023年7月9日 22:27
收件人: 592767809/video_server
抄送: whj13142020; Comment
主题: Re: [592767809/video_server] 无法下载微信视频号 (Issue #2)

发现一个问题，“微信视频号：key已被重置” 这句话没有出现，是什么原因，有提示代理开启成功
代理没有开启成功，或者是缓存没有被清理
