### ISSUE TITLE
我使用的时候遇到的一些问题。

### ISSUE THREAD

**Issue by CurtLsp** [592767809/video_server#20]
按照您的操作步骤执行完以后，提示的是HOOK开启。之后无论怎样观看视频号也抓不到地址。请问如何解决呀？

**Comment by 592767809** [comment]
> 按照您的操作步骤执行完以后，提示的是HOOK开启。之后无论怎样观看视频号也抓不到地址。请问如何解决呀？

必须进入到视频详情才能抓到
