### ISSUE TITLE
微信号是不是更新了，现在一开代理就不播放，关掉就正常

### ISSUE THREAD

**Issue by meetinnet** [592767809/video_server#25]
然后 视频屏幕还弹出一行字让你检测是否启用了代理。

**Comment by 592767809** [comment]
证书是否正确安装？带图看看

**Comment by meetinnet** [comment]
如果证书安装不正确是不是不会提示代理开启成功呀？  另外跟微信电脑客户端版本有关系吗，我用的是旧版本3.9.0.28。

![VIDEOserver](https://github.com/592767809/video_server/assets/30096780/40611f5c-7305-46c1-8588-f5777b982181)

**Comment by meetinnet** [comment]
又重新安装了一遍证书，开启代理的情况下能播放了，但是监听不到。

![Uploading VIDEOserver1.png…]()

**Comment by meetinnet** [comment]
图片没传上去怎么。
![VIDEOserver1](https://github.com/592767809/video_server/assets/30096780/084949ea-6840-42f4-8fe8-e158de4991d6)

**Comment by 592767809** [comment]
证书是否安装正确与是否提示代理开启成功没有关系，无法监听尝试删除缓存

**Comment by meetinnet** [comment]
删除缓存之后，能监听到了，但又报下载失败，，复制到浏览器也打不开。谢谢。
![video2](https://github.com/592767809/video_server/assets/30096780/61951ad6-502d-473e-a75c-d7b8b0e0cf92)
