### ISSUE TITLE
直播回放下载需求

### ISSUE THREAD

**Issue by StarryskyLL** [592767809/video_server#27]
有视频号里直播回放的下载需求
作者大大能尝试支持一下吗

**Comment by 592767809** [comment]
直播回放的是没有加密的，抓包可以直接下载

**Comment by StarryskyLL** [comment]
> 直播回放的是没有加密的，抓包可以直接下载

刚才尝试了一下，应该是抓到了，但是不知道用什么工具下载

**Comment by StarryskyLL** [comment]
不是很会抓包，在root机上用了小黄鸟，开了HTTPS，测试过能抓到HTTPS
抓到一些返回206的包域名是`finderdsp.video.qq.com`的
拖动进度条播放的时候也是抓到这个域名的其他包
贴其中一个包的参数,但是都是用的http

请求
```
GET /251/20302/stodownload?X-snsvideoflag=xWT156&bizid=1023&cdnkey=Cvvj5Ix3eewK0tHtibORqcsqchXNh0Gf3sJcaYqC2rQAgELiaUBIByBhua0JSQ9adsgJoFTvHx05XJP57bkvib57ICcNhuAsV8XB1FBzNoKeUJhLsc7j5lUIibC3ZeDzEKrh&cdntoken=jiW1us0Z2LbBSXQTtLAMJGo9eiyXYAkoqCwFP-Op4f9ALAiIuRUGM2yjui5QH5G2&ctsc=32&dotrans=0&extg=4eaf00&hvf=0&hy=SH&inm=f57c1e85c674721be2081e8cb75ed432&m=&svrbypass=AAuL/QsFAAABAAAAAACUwN/6g4wbWZrkoszgZRAAAADnaHZTnGbFfAj9RgZXfw6VT27zQPaU2UHnoOHeceV1y8qIVLPkTZKu8M+mNKDJ15WAjlpFKBIwN40=&svrnonce=1709231266&taskid=3439437132547911745&tokenidx=1&upid=500220&end=1&mkey=2&rh-key=aojcgv9y0&sche_type=7 HTTP/1.1
Accept: */*
C-Seq: 78
Cache-Control: no-cache
Connection: Keep-Alive
Content-Type: application/octet-stream
Host: findergdtyy.video.qq.com
Range: bytes=8110080-8372223
User-Agent: MicroMessenger Client
X-Client-Os: android-33
X-Client-Version: 28002F35
X-Reserve: STFPMkpDRFY0YmJiSGVzZTNDaU1ncjVtRFNCeFVoeDJ1RUtNaTcyOGhpbz0=
```
响应
```
HTTP/1.1 206 Partial Content
Server: openresty
Date: Thu, 29 Feb 2024 19:21:51 GMT
Content-Type: video/mp4
Content-Length: 262144
Connection: keep-alive
X-Verify-Code: fdc4d9d5ba78e83c556d9ee33610fc3a
X-snsvideoflag: xWT156
x-videoerrno: 0
X-Cache-Lookup: Cache Hit
Last-Modified: Tue, 27 Feb 2024 12:58:26 GMT
Cache-Control: max-age=31536000
Content-Range: bytes 8110080-8372223/32501488
X-NWS-LOG-UUID: 6270197870479396992
X-Cache-Lookup: Cache Miss
CacheKey: findercdn.video.qq.com/Cvvj5Ix3eewK0tHtibORqcsqchXNh0Gf3sJcaYqC2rQAgELiaUBIByBhua0JSQ9adsgJoFTvHx05XJP57bkvib57ICcNhuAsV8XB1FBzNoKeUJhLsc7j5lUIibC3ZeDzEKrh/xWT156/
X-DBUEG-MISS-HEADER: on
X-ServerIp: ***.***.***.***
Client-Ip: ***.***.***.***
X-encflag: 0
X-enclen: 0
Age: 3233
Ctl-Cache-Status: HIT from jx-nanchang11-ca60, HIT from gx-beihai2-ca05
Request-Id: 65e0d94f0ac2e4be41bae0a856c6d863
X-CDN: gdtyy
X-traceid: caf351eb-0907-de56-c812-6b08d6fa142d
```

**Comment by 592767809** [comment]
在响应头中看到X-encflag: 0，可以确定就是非加密的。

其实可以直接在电脑端抓包，简单很多。抓到的地址直接给浏览器下载就可以，想快一点的给idm也可以

**Comment by StarryskyLL** [comment]
> 在响应头中看到X-encflag: 0，可以确定就是非加密的。
> 
> 其实可以直接在电脑端抓包，简单很多。抓到的地址直接给浏览器下载就可以，想快一点的给idm也可以

谢谢大佬，确实可以了
我之前用手机抓到之后直接用手机浏览器访问的这个URL，提示无法打开，我以为是不正确的，甚至还觉得应该是M3U8的
刚才用电脑抓了之后直接用浏览器访问URL就可以调用IDM下载了，下载的文件没有后缀可以直接播放

**Comment by mmfan** [comment]
video_server嗅探不到回放地址。。。怎么办

**Comment by happy8090** [comment]
可以成功，但是复 提示的视频地址 用idm下载后 不能播放，文件大小和video_server下载的文件大小一样样的

**Comment by happy8090** [comment]
> video_server嗅探不到回放地址。。。怎么办
可以嗅探到的，多重试一下教程细节

**Comment by happy8090** [comment]
大哥哥 这个项目可以开源吗

**Comment by StarryskyLL** [comment]
> 可以成功，但是复 提示的视频地址 用idm下载后 不能播放，文件大小和video_server下载的文件大小一样样的

域名是`finderdsp.video.qq.com`的吗？
先复制到浏览器看看能不能打开，浏览器打开是个视频就可以
装IDM的浏览器插件，把URL复制到浏览器等他调用IDM，我是这样的

**Comment by StarryskyLL** [comment]
> 可以成功，但是复 提示的视频地址 用idm下载后 不能播放，文件大小和video_server下载的文件大小一样样的

噢，不能播放是吧，下载下来的文件都没有后缀的，要自己添加MP4后缀
复制到浏览器里面能看的话就是对的。
是直播回放没有加密，视频什么的还是要用video_server

**Comment by StarryskyLL** [comment]
> video_server嗅探不到回放地址。。。怎么办

按照[592767809]大佬说的，video_server并没有抓直播回放地址，直播回放是没有加密的，我也抓到了。
建议用PC来抓包，不知道用什么工具的话，这里有个最近比较新的抓包工具`https://github.com/wanghongenpin/network_proxy_flutter`
我的方法是：打开需要抓的直播回放，暂停，然后开始抓包，返回到播放页继续播放视频，拖动进度条，让他有下载视频块的动作，就能抓到了，一般是状态码206，然后这个`Content-Type: video/mp4`的就是抓到的地址，直接把URL复制到浏览器，打开是视频就可以，下载的文件是没有后缀的，需要自己手动修改文件名

**Comment by 592767809** [comment]
> 可以成功，但是复 提示的视频地址 用idm下载后 不能播放，文件大小和video_server下载的文件大小一样样的

地址仅用于提示下载网络路径，视频是加密的，需要解密后才能播放。项目不会开源
