### ISSUE TITLE
能下载，但是文件打不开，报错

### ISSUE THREAD

**Issue by haiyihanmam** [592767809/video_server#28]
![tmp33A9](https://github.com/592767809/video_server/assets/94858991/2e6b03a6-f660-4350-8c2f-38055e2309fb)
您好，我按照要求做的，但是下下来的文件打不开，不知道为什么，请您方便时看一下，谢谢！

**Comment by 592767809** [comment]
是否使用最新版本，是否已经提示下载完成，使用什么播放器

**Comment by haiyihanmam** [comment]
报告，软件是最新版本1.0.6 ，下载完成，potplayer播放器 试着下了好几个都是播放错误，所以感觉是哪一步出了问题。另外我也重新安装试了下还是不行。请您方便时再看看了 微信是最新版本



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月12日 18:07 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [592767809/video_server] 能下载，但是文件打不开，报错 (Issue #28) |

是否使用最新版本，是否已经提示下载完成，使用什么播放器

**Comment by 592767809** [comment]
刚刚测试3.9.9.43微信版本，下载播放正常

**Comment by haiyihanmam** [comment]
好的 刚又按照步骤重新安装设置了一次，这次微信视频号直接打不开了，转圈圈，然后显示网络错误，不是提示不安全，我准备把微信和软件都卸载掉，重新装一下。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月13日 09:20 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [592767809/video_server] 能下载，但是文件打不开，报错 (Issue #28) |

刚刚测试3.9.9.43微信版本，下载播放正常
