### ISSUE TITLE
视频号不能下载

### ISSUE THREAD

**Issue by asd6fds** [592767809/video_server#46]
启动一切正常，开启代理成功 开启监听 8887忽略域名： 开启服务 8777。
但是视频号视频播放，软件没有任何提示。不能下载视频

**Comment by wqe124433** [comment]
一样的问题

**Comment by 592767809** [comment]
微信客户端版本号+软件版本号+软件运行界面截图

**Comment by asd6fds** [comment]
微信 3.9.11.25，server_v1.0.7
















在 2024-08-05 09:47:41，"漁滒" ***@***.***> 写道：

微信客户端版本号+软件版本号+软件运行界面截图

**Comment by 592767809** [comment]
更测试了一下，确实无法下载，等待修复

**Comment by 592767809** [comment]
> 微信 3.9.11.25，server_v1.0.7 在 2024-08-05 09:47:41，"漁滒" ***@***.***> 写道： 微信客户端版本号+软件版本号+软件运行界面截图 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

使用更新的1.0.8重试

**Comment by chengsanjing** [comment]
刚刚使用1.0.8的版本试了。我的微信版本是3.9.7.29。还是没反应。

**Comment by 592767809** [comment]
清除缓存重试

**Comment by asd6fds** [comment]
1.0.8，视频号可以下载了，感谢

















在 2024-08-05 14:19:35，"漁滒" ***@***.***> 写道：

微信 3.9.11.25，server_v1.0.7 在 2024-08-05 09:47:41，"漁滒" @.> 写道： 微信客户端版本号+软件版本号+软件运行界面截图 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>

使用更新的1.0.8重试

**Comment by chengsanjing** [comment]
> 清除缓存重试

![cb6f8cacb54699991aa7ea3c6ee7f03180fec122c9c62771e08c65e5f5fe6b60QzpcVXNlcnNcY2hlbmcueHVcQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDQ0NzIwNTgwNF92MlxJbWFnZUZpbGVzXDE3MjI4NTIxNjAzNTZfQTE1NENFMTAtNEIyRi00OTgwLUIyMDUtM0Y1Nzc1MzZENDc5LnBuZw==](https://github.com/user-attachments/assets/af117ed6-e000-46d2-b001-d238f614d66f)


![25d72635203330073992d37457dc40a63c64aa784aaf1bd4f4ed3e45edd1a34aQzpcVXNlcnNcY2hlbmcueHVcQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDQ0NzIwNTgwNF92MlxJbWFnZUZpbGVzXDE3MjI4NTIxODg2MDVfOTFEMjI1RDYtNEI0RS00M2UzLUE4NTctQ0UxOUEwOTIwMEM0LnBuZw==](https://github.com/user-attachments/assets/95379aaf-a481-429f-969e-1cc44cc32e78)


是清除微信里的缓存吗？已经清除了。只显示HOOK功能已开启

**Comment by 592767809** [comment]
> > 清除缓存重试
> 
> ![cb6f8cacb54699991aa7ea3c6ee7f03180fec122c9c62771e08c65e5f5fe6b60QzpcVXNlcnNcY2hlbmcueHVcQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDQ0NzIwNTgwNF92MlxJbWFnZUZpbGVzXDE3MjI4NTIxNjAzNTZfQTE1NENFMTAtNEIyRi00OTgwLUIyMDUtM0Y1Nzc1MzZENDc5LnBuZw==](https://private-user-images.githubusercontent.com/52806609/355062788-af117ed6-e000-46d2-b001-d238f614d66f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MTA3MDcsIm5iZiI6MTcyMjkxMDQwNywicGF0aCI6Ii81MjgwNjYwOS8zNTUwNjI3ODgtYWYxMTdlZDYtZTAwMC00NmQyLWIwMDEtZDIzOGY2MTRkNjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAyMTMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1YzVlZTY4OGMwOTExZWJjN2RmM2JkYjc4MTM0YmI0NjFhMDgzOGE4NWNjZDA1ZWNkMDdhMzIyZWE0YTY3Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oDNk7gwGZ_-mOrX4R1SJSzQQrwlWtkk3vDypUM4SKNk)
> 
> ![25d72635203330073992d37457dc40a63c64aa784aaf1bd4f4ed3e45edd1a34aQzpcVXNlcnNcY2hlbmcueHVcQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDQ0NzIwNTgwNF92MlxJbWFnZUZpbGVzXDE3MjI4NTIxODg2MDVfOTFEMjI1RDYtNEI0RS00M2UzLUE4NTctQ0UxOUEwOTIwMEM0LnBuZw==](https://private-user-images.githubusercontent.com/52806609/355062871-95379aaf-a481-429f-969e-1cc44cc32e78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MTA3MDcsIm5iZiI6MTcyMjkxMDQwNywicGF0aCI6Ii81MjgwNjYwOS8zNTUwNjI4NzEtOTUzNzlhYWYtYTQ4MS00MjlmLTk2OWUtMWNjNDRjYzMyZTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAyMTMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNjUyNGQxZDA3NzA0N2M4ZGU1ZGFmNGNiNjk0MTdlNjdlZjgyYTA3NjNlOTgxNGNiMDg1NTM3MGY0MzFhZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ToSJ7tsdA6WpvHKepPQzY-AjlPT2GASgC67DbV5bb_I)
> 
> 是清除微信里的缓存吗？已经清除了。只显示HOOK功能已开启

出现【HOOK功能已开启】证明已经可以了。尝试进入到页面详情，或者尝试更新微信客户端版本

**Comment by chengsanjing** [comment]
> > > 清除缓存重试
> > 
> > 
> > ![cb6f8cacb54699991aa7ea3c6ee7f03180fec122c9c62771e08c65e5f5fe6b60QzpcVXNlcnNcY2hlbmcueHVcQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDQ0NzIwNTgwNF92MlxJbWFnZUZpbGVzXDE3MjI4NTIxNjAzNTZfQTE1NENFMTAtNEIyRi00OTgwLUIyMDUtM0Y1Nzc1MzZENDc5LnBuZw==](https://private-user-images.githubusercontent.com/52806609/355062788-af117ed6-e000-46d2-b001-d238f614d66f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MTA3MDcsIm5iZiI6MTcyMjkxMDQwNywicGF0aCI6Ii81MjgwNjYwOS8zNTUwNjI3ODgtYWYxMTdlZDYtZTAwMC00NmQyLWIwMDEtZDIzOGY2MTRkNjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAyMTMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1YzVlZTY4OGMwOTExZWJjN2RmM2JkYjc4MTM0YmI0NjFhMDgzOGE4NWNjZDA1ZWNkMDdhMzIyZWE0YTY3Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oDNk7gwGZ_-mOrX4R1SJSzQQrwlWtkk3vDypUM4SKNk)
> > ![25d72635203330073992d37457dc40a63c64aa784aaf1bd4f4ed3e45edd1a34aQzpcVXNlcnNcY2hlbmcueHVcQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDQ0NzIwNTgwNF92MlxJbWFnZUZpbGVzXDE3MjI4NTIxODg2MDVfOTFEMjI1RDYtNEI0RS00M2UzLUE4NTctQ0UxOUEwOTIwMEM0LnBuZw==](https://private-user-images.githubusercontent.com/52806609/355062871-95379aaf-a481-429f-969e-1cc44cc32e78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MTA3MDcsIm5iZiI6MTcyMjkxMDQwNywicGF0aCI6Ii81MjgwNjYwOS8zNTUwNjI4NzEtOTUzNzlhYWYtYTQ4MS00MjlmLTk2OWUtMWNjNDRjYzMyZTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAyMTMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNjUyNGQxZDA3NzA0N2M4ZGU1ZGFmNGNiNjk0MTdlNjdlZjgyYTA3NjNlOTgxNGNiMDg1NTM3MGY0MzFhZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ToSJ7tsdA6WpvHKepPQzY-AjlPT2GASgC67DbV5bb_I)
> > 是清除微信里的缓存吗？已经清除了。只显示HOOK功能已开启
> 
> 出现【HOOK功能已开启】证明已经可以了。尝试进入到页面详情，或者尝试更新微信客户端版本

好的，谢谢，已经可以了。我之前一直用看过的那些在试。后来我手动点那些没有看过的，就可以了。但是之前已经看过的，还是拦截不到，这个是缓存问题了。
