### ISSUE TITLE
Download link, displaying "Service internal error" and "Sharing has expired".

### ISSUE THREAD

**Issue by gzasyf** [592767809/video_server#48]
Download link: https://www.123pan.cn/s/6dWtVv-FZC4h.html The 123 cloud drive cannot be opened, displaying "Service internal error" and "Sharing has expired".

**Comment by Topdear** [comment]
+1

**Comment by miloyes** [comment]
+1

**Comment by 592767809** [comment]
> Download link: https://www.123pan.cn/s/6dWtVv-FZC4h.html The 123 cloud drive cannot be opened, displaying "Service internal error" and "Sharing has expired".

已更新

**Comment by gzasyf** [comment]
感谢！
