### ISSUE TITLE
代理成功，hook成功，但拦截不了视频

### ISSUE THREAD

**Issue by miloyes** [592767809/video_server#50]
最新版(3.9.12.17)的微信貌似没有这个目录了：  C:\Users\【用户名】\AppData\Roaming\Tencent\WeChat\radium\web\profiles\multitab_【32位英文数字】\Cache\Cache_Data

按以前的操作方式，代理开启成功，hook成功，但就是拦截视频没有反应！！

**Comment by wqe124433** [comment]
1.0.9版本显示HOOK功能已开启，但是下载不了，烦请大佬看下

**Comment by dchina** [comment]
我也是无法下载，以前1.0.3~1.0.7使用的老用户，1.0.9好像要启动M3U8 V1.4.8 0508.exe，我也安装步骤提前启动了。
问题研究。

**Comment by miloyes** [comment]
可能不是video serer的版本问题，应该是微信升级后失效了，发现这个问题后我试着用1.0.7版本，也是显示代理成功，监听成功，微信Hook成功，但就是下载不了视频。

**Comment by miloyes** [comment]
补一张截图看看，就是这个样子！

![33](https://github.com/user-attachments/assets/77b26cab-5e78-44f1-9d5d-35eec21c286a)

**Comment by 592767809** [comment]
使用1.0.10版本重试，最新版微信缓存目录修改为： C:\Users\【用户名】\AppData\Roaming\Tencent\WeChat\radium\web\profiles\multitab_【32位英文数字】\Code Cache\js

**Comment by dchina** [comment]
> 使用1.0.10版本重试，最新版微信缓存目录修改为： C:\Users\【用户名】\AppData\Roaming\Tencent\WeChat\radium\web\profiles\multitab_【32位英文数字】\Code Cache\js

可以用了。另外 这个 M3U8 V1.4.8 0508.exe  好像不需要呀。

**Comment by 592767809** [comment]
> > 使用1.0.10版本重试，最新版微信缓存目录修改为： C:\Users\【用户名】\AppData\Roaming\Tencent\WeChat\radium\web\profiles\multitab_【32位英文数字】\Code Cache\js
> 
> 可以用了。另外 这个 M3U8 V1.4.8 0508.exe  好像不需要呀。

不是所有功能都需要用到的，某些m3u8下载才需要用到下载器

**Comment by miloyes** [comment]
> 使用1.0.10版本重试，最新版微信缓存目录修改为： C:\Users\【用户名】\AppData\Roaming\Tencent\WeChat\radium\web\profiles\multitab_【32位英文数字】\Code Cache\js

可以下载了，谢谢哈
