### ISSUE TITLE
1.0.10 开启Hook失败！

### ISSUE THREAD

**Issue by miloyes** [592767809/video_server#51]
这才没用几天的功夫。又不能用了。见下图：

![986](https://github.com/user-attachments/assets/b2ed0510-3a48-41fb-b1ac-b8e31cd5e134)

**Comment by 592767809** [comment]
刚刚测试了微信客户端版本3.9.12.17，可以正常下载

**Comment by sdieedu** [comment]
win10 64 打不开新版本， 旧版本可以打开咋回事

**Comment by 18636476026** [comment]
我也是开启HOOK失败，用的3.9.12.17版本

**Comment by miloyes** [comment]
> 刚刚测试了微信客户端版本3.9.12.17，可以正常下载

我这边一直是hook失败。3.9.12.17版本。

**Comment by Jieoz** [comment]
求更新求更新

**Comment by 592767809** [comment]
> > 刚刚测试了微信客户端版本3.9.12.17，可以正常下载
> 
> 我这边一直是hook失败。3.9.12.17版本。

奇怪了，我有空再测试一下

**Comment by miloyes** [comment]
> > > 刚刚测试了微信客户端版本3.9.12.17，可以正常下载
> > 
> > 
> > 我这边一直是hook失败。3.9.12.17版本。
> 
> 奇怪了，我有空再测试一下


今天又试了一下，还是不行，HOOK失败！  我的目录下出现了两个（   multitab_【32位英文数字】 ）   的目录，我在启动前，把这两个都删了，还是不行，依然HOOK失败！

**Comment by 592767809** [comment]
使用最新的1.0.11版本重试

**Comment by miloyes** [comment]
> 使用最新的1.0.11版本重

ok，可以正常使用了。
