### ISSUE TITLE
hook失败

### ISSUE THREAD

**Issue by pusuxing** [592767809/video_server#52]
以前1.0.8版本的时候，问题不大，可以很好的使用，现在退回微3.9.5版本还是出现这个问题，证书也重新安装了！
![hook失败](https://github.com/user-attachments/assets/105743cf-407c-4a8b-ba4d-36ca7a66d208)

**Comment by miloyes** [comment]
+1

**Comment by wqe124433** [comment]
是的，hook失败

**Comment by 592767809** [comment]
https://github.com/592767809/video_server/issues/51#issuecomment-2449164514
