### ISSUE TITLE
微信：HOOK功能开启失败，无法HOOK文件，请联系作者

### ISSUE THREAD

**Issue by Xingxiwei** [592767809/video_server#53]
微信：HOOK功能开启失败，无法HOOK文件，请联系作者

**Comment by 592767809** [comment]
https://github.com/592767809/video_server/issues/51#issuecomment-2449164514

**Comment by pusuxing** [comment]
可hook， 新合成的视频无法播放，类似于无法解密或者解密失效。无法预览和播放，在新生成的瞬间可见缩略图，合成之后无法播放！3.9.5版本和最新版本都是。

**Comment by 592767809** [comment]
> 可hook， 新合成的视频无法播放，类似于无法解密或者解密失效。无法预览和播放，在新生成的瞬间可见缩略图，合成之后无法播放！3.9.5版本和最新版本都是。

测试了几个视频，都可以正常下载。按照描述来看，有可能是因为视频本身并未存在加密，但被错误的认为有加密，具体是哪个视频？标题为什么？

**Comment by pusuxing** [comment]
> 

重新安装证书后解决了,可能昨天电脑没有重启的缘故!

**Comment by Xingxiwei** [comment]
世间万物负阴而抱阳#读书#黄帝内经、警惕美西方鼓动“以满代华”#清朝#明朝#剃发易服、被某些人误导的碳水 #养生#碳水#减肥#中老年#传统文化#补气#道法养生#五谷，这三个都死提示错误，其他方法都试过了除了重装windows没有试过
&nbsp;


Hey
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月1日(星期五) 上午9:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [592767809/video_server] 微信：HOOK功能开启失败，无法HOOK文件，请联系作者 (Issue #53)














  
可hook， 新合成的视频无法播放，类似于无法解密或者解密失效。无法预览和播放，在新生成的瞬间可见缩略图，合成之后无法播放！3.9.5版本和最新版本都是。
  
测试了几个视频，都可以正常下载。按照描述来看，有可能是因为视频本身并未存在加密，但被错误的认为有加密，具体是哪个视频？标题为什么？

**Comment by 592767809** [comment]
> 世间万物负阴而抱阳#读书#黄帝内经、警惕美西方鼓动“以满代华”#清朝#明朝#剃发易服、被某些人误导的碳水 #养生#碳水#减肥#中老年#传统文化#补气#道法养生#五谷，这三个都死提示错误，其他方法都试过了除了重装windows没有试过 &nbsp; Hey ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年11月1日(星期五) 上午9:34 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [592767809/video_server] 微信：HOOK功能开启失败，无法HOOK文件，请联系作者 (Issue #53) 可hook， 新合成的视频无法播放，类似于无法解密或者解密失效。无法预览和播放，在新生成的瞬间可见缩略图，合成之后无法播放！3.9.5版本和最新版本都是。 测试了几个视频，都可以正常下载。按照描述来看，有可能是因为视频本身并未存在加密，但被错误的认为有加密，具体是哪个视频？标题为什么？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

已测试，都是可以正常下载，正常播放

**Comment by Xingxiwei** [comment]
警惕美西方鼓动“以满代华”#清朝#明朝#剃发易服，如这个今天的就出现，以下内容了【2024-11-07 09:22:37】 开启代理成功
 
【2024-11-07 09:22:38】 本软件免费使用，发布地址：https://github.com/592767809/video_server
 
【2024-11-07 09:22:38】 如你付款获取本软件，请立即申请退款并且差评
 
【2024-11-07 09:22:38】 开启监听 8887
 
【2024-11-07 09:22:38】 忽略域名： 
 
www.4399.com
 
【2024-11-07 09:22:38】 开启服务 8777
 
【2024-11-07 09:25:42】 捕获链接: https://pl.qcheng.cc/Cache/mytv/413c6dd176c9a18af657e52275be25f6.m3u8
 
【2024-11-07 09:25:44】 推送失败
 
【2024-11-07 09:32:14】 微信：HOOK功能开启失败，无法HOOK文件，请联系作者
&nbsp;


Hey
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月5日(星期二) 上午9:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [592767809/video_server] 微信：HOOK功能开启失败，无法HOOK文件，请联系作者 (Issue #53)














  
世间万物负阴而抱阳#读书#黄帝内经、警惕美西方鼓动“以满代华”#清朝#明朝#剃发易服、被某些人误导的碳水 #养生#碳水#减肥#中老年#传统文化#补气#道法养生#五谷，这三个都死提示错误，其他方法都试过了除了重装windows没有试过 &nbsp; Hey @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年11月1日(星期五) 上午9:34 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [592767809/video_server] 微信：HOOK功能开启失败，无法HOOK文件，请联系作者 (Issue #53) 可hook， 新合成的视频无法播放，类似于无法解密或者解密失效。无法预览和播放，在新生成的瞬间可见缩略图，合成之后无法播放！3.9.5版本和最新版本都是。 测试了几个视频，都可以正常下载。按照描述来看，有可能是因为视频本身并未存在加密，但被错误的认为有加密，具体是哪个视频？标题为什么？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
已测试，都是可以正常下载，正常播放

**Comment by pusuxing** [comment]
> 警惕美西方鼓动“以满代华”#清朝#明朝#剃发易服，如这个今天的就出现，以下内容了【2024-11-07 09:22:37】 开启代理成功 【2024-11-07 09:22:38】 本软件免费使用，发布地址：https://github.com/592767809/video_server 【2024-11-07 09:22:38】 如你付款获取本软件，请立即申请退款并且差评 【2024-11-07 09:22:38】 开启监听 8887 【2024-11-07 09:22:38】 忽略域名： [www.4399.com](http://www.4399.com) 【2024-11-07 09:22:38】 开启服务 8777 【2024-11-07 09:25:42】 捕获链接: https://pl.qcheng.cc/Cache/mytv/413c6dd176c9a18af657e52275be25f6.m3u8 【2024-11-07 09:25:44】 推送失败 【2024-11-07 09:32:14】 微信：HOOK功能开启失败，无法HOOK文件，请联系作者 &nbsp; Hey ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年11月5日(星期二) 上午9:14 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [592767809/video_server] 微信：HOOK功能开启失败，无法HOOK文件，请联系作者 (Issue #53) 世间万物负阴而抱阳#读书#黄帝内经、警惕美西方鼓动“以满代华”#清朝#明朝#剃发易服、被某些人误导的碳水 #养生#碳水#减肥#中老年#传统文化#补气#道法养生#五谷，这三个都死提示错误，其他方法都试过了除了重装windows没有试过 &nbsp; Hey @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年11月1日(星期五) 上午9:34 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [592767809/video_server] 微信：HOOK功能开启失败，无法HOOK文件，请联系作者 (Issue #53) 可hook， 新合成的视频无法播放，类似于无法解密或者解密失效。无法预览和播放，在新生成的瞬间可见缩略图，合成之后无法播放！3.9.5版本和最新版本都是。 测试了几个视频，都可以正常下载。按照描述来看，有可能是因为视频本身并未存在加密，但被错误的认为有加密，具体是哪个视频？标题为什么？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 已测试，都是可以正常下载，正常播放 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;



经测试，部分确实不可以下载成功，部分可以删除下载的不可播放内容，重新下载即可解决，另外，不要同时打开多个视频，一个一个的下载，关闭视频号窗口重新打开播放。

**Comment by Xingxiwei** [comment]
好的明白谢谢
&nbsp;


Hey
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月7日(星期四) 晚上11:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [592767809/video_server] 微信：HOOK功能开启失败，无法HOOK文件，请联系作者 (Issue #53)














  
警惕美西方鼓动“以满代华”#清朝#明朝#剃发易服，如这个今天的就出现，以下内容了【2024-11-07 09:22:37】 开启代理成功 【2024-11-07 09:22:38】 本软件免费使用，发布地址：https://github.com/592767809/video_server 【2024-11-07 09:22:38】 如你付款获取本软件，请立即申请退款并且差评 【2024-11-07 09:22:38】 开启监听 8887 【2024-11-07 09:22:38】 忽略域名： www.4399.com 【2024-11-07 09:22:38】 开启服务 8777 【2024-11-07 09:25:42】 捕获链接: https://pl.qcheng.cc/Cache/mytv/413c6dd176c9a18af657e52275be25f6.m3u8 【2024-11-07 09:25:44】 推送失败 【2024-11-07 09:32:14】 微信：HOOK功能开启失败，无法HOOK文件，请联系作者 &nbsp; Hey @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年11月5日(星期二) 上午9:14 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [592767809/video_server] 微信：HOOK功能开启失败，无法HOOK文件，请联系作者 (Issue #53) 世间万物负阴而抱阳#读书#黄帝内经、警惕美西方鼓动“以满代华”#清朝#明朝#剃发易服、被某些人误导的碳水 #养生#碳水#减肥#中老年#传统文化#补气#道法养生#五谷，这三个都死提示错误，其他方法都试过了除了重装windows没有试过 &nbsp; Hey @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年11月1日(星期五) 上午9:34 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [592767809/video_server] 微信：HOOK功能开启失败，无法HOOK文件，请联系作者 (Issue #53) 可hook， 新合成的视频无法播放，类似于无法解密或者解密失效。无法预览和播放，在新生成的瞬间可见缩略图，合成之后无法播放！3.9.5版本和最新版本都是。 测试了几个视频，都可以正常下载。按照描述来看，有可能是因为视频本身并未存在加密，但被错误的认为有加密，具体是哪个视频？标题为什么？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 已测试，都是可以正常下载，正常播放 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
经测试，部分确实不可以下载成功，部分可以删除下载的不可播放内容，重新下载即可解决，另外，不要同时打开多个视频，一个一个的下载，关闭视频号窗口重新打开播放。
