### ISSUE TITLE
微们新版3.9.6.43已失效

### ISSUE THREAD

**Issue by newtamax** [592767809/video_server#6]
软件设置都正常,新版3.9.6.37和3.9.6.43不显示key已重置

**Comment by newtamax** [comment]
降级到3.9.5.81可以了.

**Comment by 592767809** [comment]
> 软件设置都正常,新版3.9.6.37和3.9.6.43不显示key已重置

我测试使用的是3.9.6.33版本。我点击更新显示已经是最新版本了。暂时无法适配更高的版本。更新了以后会进行适配

**Comment by snowsword20** [comment]
> > 软件设置都正常,新版3.9.6.37和3.9.6.43不显示key已重置
> 
> 我测试使用的是3.9.6.33版本。我点击更新显示已经是最新版本了。暂时无法适配更高的版本。更新了以后会进行适配

我用的是3.9.6.33版本，配置正常，一直显示不出来'key已重置’

**Comment by 592767809** [comment]
> > > 软件设置都正常,新版3.9.6.37和3.9.6.43不显示key已重置
> > 
> > 
> > 我测试使用的是3.9.6.33版本。我点击更新显示已经是最新版本了。暂时无法适配更高的版本。更新了以后会进行适配
> 
> 我用的是3.9.6.33版本，配置正常，一直显示不出来'key已重置’

大概率是证书安装不正确或者代理设置异常或者端口不正确

**Comment by charleshung99** [comment]
> 降級到3.9.5.81就可以了。

降回到3.9.5.81還是显示不出来'key已重置
