### ISSUE TITLE
只有我视频下载失败吗

### ISSUE THREAD

**Issue by whj13142020** [592767809/video_server#9]
之前可以正常下载，现在应该是微信做了更新，启动软件能显示KEY已重置，打开视频号视频，就没有然后了，没有显示捕获地址和视频下载，大家可以正常使用吗 3730862@QQ.com

**Comment by 592767809** [comment]
> 之前可以正常下载，现在应该是微信做了更新，启动软件能显示KEY已重置，打开视频号视频，就没有然后了，没有显示捕获地址和视频下载，大家可以正常使用吗 [3730862@QQ.com](mailto:3730862@QQ.com)

你的微信版本号详细是多少？

**Comment by whj13142020** [comment]
鱼哥，我删除了新版微信，用回3.9.6. 版本就可以下载了，这是我用过的最好的下载软件，谢谢

发自我的iPhone

**Comment by 592767809** [comment]
> 鱼哥，我删除了新版微信，用回3.9.6. 版本就可以下载了，这是我用过的最好的下载软件，谢谢 发自我的iPhone
> […](#)
> 在 2023年10月7日，14:59，漁滒 ***@***.***> 写道： ﻿ 之前可以正常下载，现在应该是微信做了更新，启动软件能显示KEY已重置，打开视频号视频，就没有然后了，没有显示捕获地址和视频下载，大家可以正常使用吗 ***@***.*** 你的微信版本号详细是多少？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

高版本也是支持的，只是微信缓存路径可能不一样，例如3.9.7.29，路径如下
C:\Users\【用户名】\AppData\Roaming\Tencent\WeChat\radium\web\profiles\multitab_【32位英文数字】\Cache\Cache_Data
